# Tap repos
tap josegonzalez/homebrew-php

install ant
install grc
install coreutils
install spark
install git-flow
install git-extras
install brew-cask
install cabal-install
install php55
install php55-mcrypt
install ctags
install autojump
install phantomjs
install casperjs --devel
install boot2docker
